# Generated by Django 6.0.8 on 2026-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_called',
            field=models.BooleanField(default=False, help_text='Customer has been called to pick up'),
        ),
    ]
