# Generated by Django 6.0.8 on 2026-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order_called_at_order_is_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_expires_at',
            field=models.DateTimeField(blank=True, help_text='Cart auto-expires after 5 minutes of inactivity', null=True),
        ),
    ]
