# Generated by Django 6.0.8 on 2026-08-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_cart_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.IntegerField(default=0, help_text='Discount percentage (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in hot deals section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hot_deal', to='menu.menuitem')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
