# Generated by Django 6.0.8 on 2026-08-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_hotdeal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotDeal',
        ),
    ]
