# Generated by Django 6.0.8 on 2026-08-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_table_qr_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_message', models.CharField(default='Welcome to BurgerBills • Table {table_number} • Explore our delicious menu and enjoy seamless ordering', help_text="Use {table_number} to display the customer's table number.", max_length=300)),
                ('staff_message', models.CharField(default='New Beef Gyro • Buy 2, Get 1 Free • New Chicken Gyro', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Marquee settings',
            },
        ),
    ]
