# Generated by Django 6.0.8 on 2026-08-23 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_marqueesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='menu_access_timeout_minutes',
            field=models.IntegerField(default=30, help_text='Customer menu access expires after this many minutes of inactivity'),
        ),
        migrations.AddField(
            model_name='table',
            name='qr_code_generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when QR code was last generated'),
        ),
    ]
