# Generated by Django 6.0.8 on 2026-08-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_table_menu_access_timeout_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='menu_access_timeout_minutes',
            field=models.IntegerField(default=60, help_text='Customer menu access expires after this many minutes of inactivity'),
        ),
    ]
