# Generated by Django 6.0.8 on 2026-08-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_table_menu_access_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_sizes',
            field=models.BooleanField(default=False, help_text='Enable size options (S, M, L)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size_large_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for large size', max_digits=8),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size_medium_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for medium size', max_digits=8),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size_small_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for small size', max_digits=8),
        ),
    ]
